apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: nodeapp:fixed
        imagePullPolicy: Never  # CRITICAL for Minikube local images
        ports:
        - containerPort: 3000
        # NO command: section here - Dockerfile CMD will run
